### ISSUE TITLE
[ENH] Specify output resolution in 3 dimensions

### ISSUE THREAD

**Issue by fredrmag** [PennBBL/qsiprep#109]
Hi,

When processing our dwi data we would like to keep the output data the same resolution as the input (as mentioned earlier in #15 [here](https://github.com/PennBBL/qsiprep/issues/15#issuecomment-514786234)). To my understanding, this can only be done now if your data has isotropic voxels, as the` --output-resolution` flag only takes one number as an input.

Some of our data has been acquired with anisotropic voxel size of 1.96 mm x 1.96 mm x 2.6 mm. Is it possible to keep output resolution the same as the input resolution in this case? If not, is this something that would be hard to implement?

Regards,
Fredrik

**Comment by mattcieslak** [comment]
Hi! We've kept that out for now because most tractography and reconstruction methods assume isotropic voxels. I'm not sure if we're ever going to support anisotropic voxel outputs because of this. Are you more comfortable resampling your data to isotropic an voxel size or violating the assumptions of some of the methods in the reconstruction workflows?

**Comment by fredrmag** [comment]
Thank you for your response. Our thought was to do as little as possible to the data before we supply it to FSLs TBSS. There, data is resampled to 1mm isotropic voxels. So, resampling to isotropic voxels in qsiprep might not matter.
