### ISSUE TITLE
Conceptual question regarding QSIprep normalization 

### ISSUE THREAD

**Issue by dlevitas** [PennBBL/qsiprep#114]
I've been testing out qsiprep and have a question regarding the b0 normalization to MNI space. I should preface this by saying that I'm relatively new to dMRI, so I may be misunderstanding something.

From reading the [documentation](https://qsiprep.readthedocs.io/en/latest/), the b0 reference image is co-registered to the skull-stripped T1w, and then normalized to the MNI template. I was wondering why this step occurs, since I thought doing so leads to the tensor information not being preserved. My impression is that it's standard to generate the FA images and aligning those to the template space. 

Thanks for the clarification

**Comment by mattcieslak** [comment]
Thanks for your question. This documentation is a leftover from the fmriprep and needs to be updated (would you mind opening an issue for this?).

The preprocessing pipeline uses spatial normalization to the MNI template only for 
 1. If fieldmapless distortion correction is used, to constrain the displacements to high-distortion regions or
 2. To warp regions from an MNI atlas into the subject's T1w space

In a future release we will make available FOD-based registration and QSDR so that spatial normalization can be done more accurately with the dwi data.

**Comment by dlevitas** [comment]
Thanks for the response, and yes, I'll open an issue for this.  Just to make sure I fully understand, spatial normalization to MNI only occurs if the ```--use-syn-sdc``` is set; otherwise everything remains in the subject's native space?

**Comment by mattcieslak** [comment]
The normalization will be calculated if you use `--force-spatial-normalization` or `--use-syn-sdc`/`--force-syn`. Although the normalization gets calculated it is not applied to any outputs unless you include `template` in `--output-spaces`. I recommend not doing this for the reasons you mention in the initial post. By default only the T1w space outputs are created. These are aligned to the T1w in world coordinates but sampled at the voxel size requested in `--output-resolution`

**Comment by dlevitas** [comment]
Created issue for this (see #117) to update documentation.
