### ISSUE TITLE
Problems specifying arguments to Docker wrapper for reconstruction

### ISSUE THREAD

**Issue by bwinsto2** [PennBBL/qsiprep#144]
Hello--thanks in advance for any help to what should be a simple issue. 

We're trying to run a reconstruction pipeline on qsiprep preprocessed data. We had no trouble running the preprocessing pipeline. For reconstruction, I tried copying virtually the same code as [the docs](https://qsiprep.readthedocs.io/en/latest/reconstruction.html#reconstruction):

<img width="359" alt="Screen Shot 2020-07-15 at 10 27 23 AM" src="https://user-images.githubusercontent.com/61159065/87558366-07162d80-c687-11ea-8b6c-a8d57144e2b5.png">
Here, there are a couple problems: first off, not all the arguments are interpreted. Second, it says output-resolution is required (which I'm fine with inputting) but if it is required for reconstruction, that should be part of the example code in the docs. When copy-and-pasting the command I wrote above, here's what happens:

<img width="811" alt="Screen Shot 2020-07-15 at 10 30 44 AM" src="https://user-images.githubusercontent.com/61159065/87558678-5fe5c600-c687-11ea-8f52-2691bc661017.png">

So, I reran a few times and realized that the wrapper stops inputting arguments after --recon-spec (for whatever reason). So, I tried running a command with --recon-spec as the last argument. It took in all the arguments but I wound up with this error:
<img width="840" alt="Screen Shot 2020-07-15 at 10 48 09 AM" src="https://user-images.githubusercontent.com/61159065/87560108-18f8d000-c689-11ea-9d98-ca634472118f.png">
Ok...that's strange because in the docs, bids_dir is one of the example arguments. 

So, I tried specifying the positional arguments the way I did when running preprocessing: 
<img width="424" alt="Screen Shot 2020-07-15 at 10 52 56 AM" src="https://user-images.githubusercontent.com/61159065/87560451-7260ff00-c689-11ea-86ec-39e3682d7afc.png">
The program actually started and it rans BIDS validation. But then quickly returned this error:
<img width="804" alt="Screen Shot 2020-07-15 at 10 54 29 AM" src="https://user-images.githubusercontent.com/61159065/87560536-902e6400-c689-11ea-88b0-4bac271c6f7f.png">

One lingering question I have is why --participant_label does not have to be specified for the reconstruction pipeline. Or does it? In the example code in the docs, it is not specified. (I tried running it with and without this argument and got the same result). 

If someone could shed some light on why we're having trouble running, we would really appreciate it. If we missed something in the docs or are making a simple error, I sincerely apologize. Happy to provide more info. 

Thanks so much!

**Comment by mohammadrashid0917** [comment]
I have also noticed the same errors in the docs - they seem to be slightly outdated in places. Indeed, it seems like --bids_dir, --output_dir, and --analysis_level can only be inferred from position.

Here is the command I have had success with: 

qsiprep-docker \
mohammad/testing/BIDS \
mohammad/testing/reconOutput \
participant \
-i pennbbl/qsiprep \
--output-resolution 2 \
--fs-license-file /mohammad/testing/license.txt \
-w /mohammad/testing/intermediateWork

I would wager that the error you're getting is either because 1) you didn't specify the analysis_level or 2) you didn't specify a work directory with the `-w` flag. Try including those and see if you get the error

It may help at times to refer to fmriprep's documentation and usage syntax, as most of qsiprep seems to try to follow it as closely as possible: https://fmriprep.org/en/stable/

Note that I am also a complete novice so no guarantees that the above command is the be-all and end-all correct one. Hope this helped!

**Comment by bwinsto2** [comment]
@mohammadrashid0917 thank you so much, brother! Specifying the positional arguments as you suggested and adding a working directory solved things. I would strongly recommend the devs update the example reconstruction code in the docs. 
Thanks again, Mohammad, for taking the time to help a stranger!
