### ISSUE TITLE
Troubleshooting Slow Workflow Creation

### ISSUE THREAD

**Issue by jrussell9000** [PennBBL/qsiprep#185]
I'm currently running the PNC data through qsiprep and finding that the workflow creation process is running _sloooowly_ - on the order of 1-2 hours to create each subject's workflow.  Running with omp_nthreads=8 and ntheads=208 (# cores available on my system).  I haven't had this throughput problem running with smaller datasets.  Looking for any advice on how to troubleshoot this...

I've noticed the substantive delay occurs here:

200924-08:01:48,133 nipype.workflow INFO:
         Using 8 threads in eddy
200924-09:22:54,795 nipype.workflow INFO:
         Combining all dwi files within each available session:

My docker call below:

docker run --rm -it -u 57059 -v /fast_scratch/jdr/license.txt:/opt/freesurfer/license.txt:ro -v /fast_scratch/jdr/PNC/BIDS_raw:/data:ro -v /fast_scratch/jdr/PNC/qsiprep_out:/out -v /fast_scratch/jdr/PNC/qsi_work:/scratch pennbbl/qsiprep:0.11.5 /data /out participant --output-resolution 1 --force-syn -w /scratch -v --skip_bids_validation

**Comment by mattcieslak** [comment]
Hi @jrussell9000, I've also noticed that workflow creation can be slow on large datasets. This is probably due to a combination of reading the huge BIDS directory and generating so many workflows. For studies with more than tens of subjects, we typically parallelize on subjects, copying or linking just their directory to its own bids directory, then running qsiprep. I'd also caution against using so many threads in a single qsiprep run because you are likely to run into memory issues that could make your system unstable, particularly if many of the subjects get to resampling steps at the same time.

**Comment by jrussell9000** [comment]
Good to know!  I'll try parallelizing things as  you suggest, thanks!

**Comment by mattcieslak** [comment]
Were you able to confirm that workflow creation went faster?

**Comment by jrussell9000** [comment]
Yes, I dialed things back to groups of 100 subjects per call and found the workflow creation sped up considerably.
