### ISSUE TITLE
Reusing outputs

### ISSUE THREAD

**Issue by araikes** [PennBBL/qsiprep#61]
Hi @mattcieslak,
I'm running `qsiprep` and I want to test out a couple of options for our lab (namely, RPE vs. Syn). I'm curious if there is a way to either:
1. Reuse `anat` outputs from fmriprep -OR-
2. Reuse `anat` outputs from qsiprep runs

That would help streamline my processing if I can just change the flags for how SDC is handled without having to fully re-run the `anat` workflow.

Thanks

**Comment by mattcieslak** [comment]
Hi @araikes! You can't re-use anat outputs from fmriprep because qsiprep orients images differently and ac-pc aligns the T1w. You can definitely re-use the anatomical workflow for multiple different versions of the dwi workflow, though. My approach to this would be

 1. Run the whole workflow using fieldmaps
 2. Copy the working directory elsewhere if you want a backup
 3. Delete the dwi_preproc_wf directory from the working directory used in (1)
 4. Run the SyN version of the pipeline specifying the same working directory from (1)

Unless you have terrible fieldmaps, I'd definitely recommend using them over SyN though. We've found that SyN gets the displacement directoin wrong in orbitofrontal sometimes.

**Comment by araikes** [comment]
That workflow makes sense and I will give it a shot.

The main motivation for my thought was comparing groups that have fieldmaps (a current dataset) with a similar one collected several years ago with fieldmaps. It's all single-shell, so SDC and HMC come down to `TOPUP/EDDY` but being able to run `TOPUP` on one group and not on the other and then trying to compare FA (for example) or tractography seems less than ideal.

**Comment by mattcieslak** [comment]
Did this work out? If so I'd like to close the issue

**Comment by araikes** [comment]
Hi @mattcieslak,

I have been able to use this method to restart failed processing runs (cluster disconnected) but I haven't gotten around to testing this specific use case. Feel free to close it and I will reopen if I run into an issue when I do test it.
