### ISSUE TITLE
Eddy branch: not-too-infrequent case that key metadata is missing for any reason 

### ISSUE THREAD

**Issue by dPys** [PennBBL/qsiprep#9]
e.g. outdated acquisitions like HNU1 do not have associated BIDS .json files (i.e. with readout, bpppe, or effective echo spacing), nor raw dicoms that are available to infer this information, nor a scan protocol with anything useful (see: http://fcon_1000.projects.nitrc.org/indi/CoRR/html/_static/scan_parameters/HNU_1_scantable.pdf). Could I PR a trigger in the eddy interface to fallback to a dummy value for the acq. params file for TOPUP and EDDY in the case that there was no reverse phase encoding performed (i.e. and thus susceptibility correction will be skipped anyway)?

@dPys

**Comment by mattcieslak** [comment]
The acqparams file gets automatically generated based on the sidecars, so I'm thinking it would be easiest for the user to add dummy fields to their sidecars so that the acqparams gets created (even if it's not correct). If possible I'd like to avoid having qsiprep automatically fill in blanks when data is missing. Legacy data curation is full of problems and should be addressed on its own outside of preprocessing. 

What if we add a section to the documentation about legacy data? It would include explicit instructions about making dummy sidecars and all the warnings that go along with it. I'd be happy to help make a standalone tool that creates dummy sidecars for legacy data. what do you think?

**Comment by dPys** [comment]
That sounds reasonable to me. I wonder-- does TOPUP/eddy consider b-value placement at all with respect to lines in the acq. params file if susceptibility correction is to be skipped entirely (as will be the case with this and other legacy data)? In other words, what would a dummy sidecar add that would be different from, say, creating a generic parameters file to use on the fly that contains just one line (e.g. -1 0 0 0.1) where the first, second and third entries change depending on the PhaseEncodingDirection which should theoretically (always) be present in the metadata?

Would be nice to see a few lines of what you have in mind, and then I can help build off it.

Cheers,
@dPys

**Comment by mattcieslak** [comment]
I think this already happens in the GatherEddyInputs interface. We can re-open this if you mean something else
