### ISSUE TITLE
Recommendations on processing

### ISSUE THREAD

**Issue by araikes** [PennBBL/qsiprep#98]
Hi @mattcieslak,

So far, processing with `qsiprep:0.7.1` is going well. Things are reconstructing and I'm not having the same issues previously identified. 

I have a specific use case question for you though. I've gotten access to a dataset where they collected multishell data in two runs on two separate sessions (both the same direction, no reverse phase encoded fieldmap). So, for both baseline and post-treatment, there is a 25 direction _b_ = 1000 shell and a 20 direction _b_ = 2000 shell, each as separate DICOM folders and therefore separate `.nii.gz` files.

Ultimately, for any diffusion analyses (TBSS, tractography) I'll need those to be a single pre-processed file. If it was a single session, I would assume I could use `--combine-all-dwi` but that's less than desirable for the multi-session set up.

Any recommendations on processing these data with QSIPrep?

**Comment by mattcieslak** [comment]
Hi @araikes,

Why is `--combine-all-dwis` less than desirable? QSIPrep won't ever combine dwis across sessions, so this flag will do what I think you want it to. The two series will be combined for motion correction, and can be denoised (unringing, bias correction, mp-pca) either together or separately with the `--denoise-before-combining` option. 

If the patients/subjects are well-behaved (do not re-position their head between the two scans), you might want to not use `--denoise-before-combining`, because mp-pca will benefit from having twice as many samples to look at. I would also recommend adding `--unringing-method mrdegibbs`.

Could you try this out and let me know if it works as intended?

**Comment by araikes** [comment]
I will definitely give it a shot. 

As for less desirable, the documentation reads: `combine dwis from across multiple runs for motion correction and reconstruction` but doesn't specify within-session only so I wasn't sure if it would combine *all* runs.

I'll definitely give it a short and let you know how it goes.

**Comment by araikes** [comment]
Alright.. a follow up question;

The dataset for this particular issue was collected on a GE and for whatever the reason does not have the phase-encoding direction or total readout times in the headers and so the JSON doesn't have that information.

I've confirmed that both shell acquisitions were one direction so I can't run `TOPUP` but QSIPrep still crashes because the `TotalReadout` is missing.

Suggestions?

**Comment by mattcieslak** [comment]
In this case I'd recommend adding those values to the json sidecars using either data from the scan pdfs or reasonable made up values. Also, could you try running 0.8.0RC2 on your oblique T1w data? They should work now without needing you to manually de-oblique them

**Comment by araikes** [comment]
Ok, that's what I figured. I'm trying to track down the scan PDFs so I can do just that.

And yes, I'll give `0.8.0RC2` a run. I was already planning on a test of it.

Thanks

**Comment by araikes** [comment]
Closed along with #106
